@echo off
echo Initializing Git...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "Initialize repository with .gitignore and README"
echo Setting branch to main...
git branch -M main
echo Adding remote origin...
git remote add origin https://github.com/editor-shannu/career-aicopilot
echo Pushing to remote...
git push -u origin main
echo Done.
pause
